version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: 
      timeout: 300
      runas: root
  AfterInstall:
    - location: 
      timeout: 300
      runas: root
  ApplicationStart:
    - location: 
    - location: 
      timeout: 300
      runas: root
  ApplicationStop:
    - location: 
      timeout: 300
      runas: root
